### ISSUE TITLE
[Error] souls sync model 

### ISSUE THREAD

**Issue by KishiTheMechanic** [elsoul/souls#7]
```
➜  api git:(frontend) souls sync model
🎉  Syncing Files...                   /Users/ktm/dev/trade-pos/config/souls.rb:5:in `block in <top (required)>'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/lib/souls.rb:34:in `configure'
/Users/ktm/dev/trade-pos/config/souls.rb:1:in `<top (required)>'
<internal:/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/lib/souls/cli/sync/model.rb:14:in `cp_and_dl_files'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/lib/souls/cli/sync/model.rb:7:in `block in model'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/lib/souls/cli/sync/model.rb:6:in `each'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/lib/souls/cli/sync/model.rb:6:in `model'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/exe/souls:152:in `public_send'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/exe/souls:152:in `block in <top (required)>'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/whirly-0.3.0/lib/whirly.rb:171:in `start'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/souls-0.48.2/exe/souls:150:in `<top (required)>'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/bin/souls:23:in `load'
/Users/ktm/.anyenv/envs/rbenv/versions/3.0.2/bin/souls:23:in `<main>'
undefined method `github_repo=' for #<Souls::Configuration:0x00007ff62bad7e78 @app="trade-pos", @project_id="usmef-japan-trade", @region=nil, @endpoint=nil, @strain="mother", @fixed_gems=[""], @workers=nil>
➜  api git:(frontend) souls -v
0.48.2
```

**Comment by POPPIN-FUMI** [comment]
`config/souls.rb` から `github_repo' が新しいバージョンから消えました。新しい `config/souls.rb` に書き換えます
